name: Bug Report

description: Create a report to help us improve

title: '[BUG] '
labels: ['bug', 'triage']

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: input
    id: summary
    attributes:
      label: Summary
      description: A brief description of the issue
      placeholder: What's wrong?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How do you trigger this bug?
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen?

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happens?

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: OS, Python version, Docker version, etc.
      placeholder: |
        - OS: 
        - Python: 
        - Docker: 

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Any error messages or stack traces

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context about the problem
