name: Feature Request

description: Suggest an idea for this project

title: '[FEATURE] '
labels: ['enhancement', 'triage']

body:
  - type: markdown
    attributes:
      value: |
        Thanks for your feature request! Please fill out the template below.

  - type: input
    id: summary
    attributes:
      label: Summary
      description: A brief description of the feature
      placeholder: What do you want to add?
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Solved
      description: What problem does this solve?

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should we implement this?

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Any alternative solutions you've considered?

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any mockups, examples, or related issues?
